/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './web/templates/**/*.html',
    './web/static/js/**/*.js',
  ],
  safelist: [
    'card', 'card-interactive', 'card-flat',
    'btn', 'btn-primary', 'btn-secondary', 'btn-ghost', 'btn-sm', 'btn-lg', 'btn-icon',
    'input', 'input-error',
    'badge', 'badge-primary', 'badge-success', 'badge-warning', 'badge-error', 'badge-info', 'badge-neutral',
    'avatar', 'avatar-sm', 'avatar-lg', 'avatar-placeholder', 'avatar-ring',
    'divider', 'divider-label',
    'link',
    'skeleton', 'skeleton-text', 'skeleton-avatar', 'skeleton-thumbnail', 'skeleton-card',
    'progress-bar',
    'toast', 'toast-container', 'toast-content', 'toast-icon', 'toast-title', 'toast-message', 'toast-close', 'toast-progress',
    'empty-state', 'empty-state-icon', 'empty-state-title', 'empty-state-text', 'empty-state-cta',
    'sidebar', 'sidebar-collapsed',
    'bottom-nav', 'bottom-nav-item',
    'theme-toggle',
    'stat-card',
    'chat-bubble', 'chat-bubble-self', 'chat-bubble-other',
    'stagger-item',
    'htmx-indicator',
    'scrollbar-thin', 'scrollbar-none',
    'text-balance', 'gradient-mesh', 'bg-dot-pattern',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
          950: '#042f2e',
        },
        surface: {
          DEFAULT: '#ffffff',
          secondary: '#fafaf9',
          tertiary: '#f5f5f4',
        },
        dark: {
          bg: '#0c0a09',
          surface: '#1c1917',
          surface2: '#292524',
          border: '#44403c',
          text: '#fafaf9',
          muted: '#a8a29e',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-in-up': 'fadeInUp 0.3s ease-out',
        'fade-in-down': 'fadeInDown 0.2s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-up': 'slideInUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-press': 'scalePress 0.15s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite linear',
        'blob': 'blob 14s ease-in-out infinite',
        'gradient': 'gradientShift 12s ease infinite',
        'count-up': 'countUp 0.4s ease-out',
        'shake': 'shake 0.5s ease-in-out',
        'spin-slow': 'spin 2s linear infinite',
        'bounce-gentle': 'bounceGentle 1s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown: { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        slideInLeft: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(0)' } },
        slideInUp: { '0%': { transform: 'translateY(100%)' }, '100%': { transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        scalePress: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(0.97)' }, '100%': { transform: 'scale(1)' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        blob: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '25%': { transform: 'translate(20px,-30px) scale(1.1)' }, '50%': { transform: 'translate(-20px,20px) scale(0.9)' }, '75%': { transform: 'translate(30px,10px) scale(1.05)' } },
        gradientShift: { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        countUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shake: { '0%,100%': { transform: 'translateX(0)' }, '10%,30%,50%': { transform: 'translateX(-2px)' }, '20%,40%': { transform: 'translateX(2px)' } },
        bounceGentle: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-3px)' } },
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 10px 25px rgba(0,0,0,0.08), 0 4px 10px rgba(0,0,0,0.04)',
        'elevated': '0 20px 60px rgba(0,0,0,0.12), 0 8px 20px rgba(0,0,0,0.06)',
        'modal': '0 25px 60px rgba(0,0,0,0.15)',
        'toast': '0 8px 32px rgba(0,0,0,0.12)',
        'nav': '0 1px 3px rgba(0,0,0,0.05)',
        'soft': '0 2px 8px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}
